### ISSUE TITLE
bot.world.setChar's color argument doesn't work

### ISSUE THREAD

**Issue by ArcticNiko** [scar17off/owot-js#1]
I can't use the colour argument on the bot.world.setChar function. Everytime I do, the character that's written stays black.

I looked through the code and it appears that setChar doesn't have the colour value at the right, which it should have, nor does it use the colour argument at all...

So this code:
```js
setChar: (char, x, y, color) => {
  if(ws.readyState !== 1) return;
  ws.send(JSON.stringify({"kind":"write","edits":[this.utils.calculateCoords(x, y).concat(this.player.color,char,144)]}));
},
```
can be swapped with:
```js
setChar: (char, x, y, color) => {
  if(ws.readyState !== 1) return;
  ws.send(JSON.stringify({"kind":"write","edits":[this.utils.calculateCoords(x, y).concat(this.player.color,char,144, color)]}));
},
```
to fix the bug.

I don't know what the this.player.color is for. At first glance, it seems useless, but I probably just don't understand it so I'm just not touching it to not break anything.

**Comment by scar17off** [comment]
ok fixed (maybe)
